/* Shared mobile primary PPG and heart rate. No DOM, camera, network or platform dependency.
 * Fixed 60 Hz output grid; filter coefficients generated by scipy.signal.butter
 * (N=3, [0.5, 5] Hz, btype='bandpass', fs=60, output='sos').
 */
(function (root) {
  'use strict';
  const FS = 60;
  const SOS = [
    [.008598686086321939, .017197372172643877, .008598686086321939, 1, -1.4520619841171416, .6596484731374982],
    [1, 0, -1, 1, -1.5903260597027793, .612800788139932],
    [1, -2, 1, 1, -1.9521679192002526, .9550513432042125]
  ];
  function mean(a) { return a.reduce((s, v) => s + v, 0) / a.length; }
  function std(a) { const m = mean(a); return Math.sqrt(mean(a.map(v => (v - m) ** 2))); }
  function percentile(a, q) {
    const b = [...a].sort((x, y) => x - y), k = (b.length - 1) * q;
    const lo = Math.floor(k), hi = Math.ceil(k);
    return b[lo] + (b[hi] - b[lo]) * (k - lo);
  }
  const median = a => percentile(a, .5);
  function detrend(a) {
    const center = (a.length - 1) / 2, m = mean(a);
    let numerator = 0, denominator = 0;
    a.forEach((v, i) => { numerator += (i - center) * (v - m); denominator += (i - center) ** 2; });
    return a.map((v, i) => v - m - numerator / denominator * (i - center));
  }
  function peaks(y, distance, prominence) {
    const candidates = [];
    for (let i = 1; i < y.length - 1; i++) {
      if (y[i] <= y[i - 1]) continue;
      let end = i;
      while (end + 1 < y.length && y[end + 1] === y[i]) end++;
      if (end + 1 < y.length && y[end + 1] < y[i]) candidates.push(Math.floor((i + end) / 2));
      i = end;
    }
    const selected = [];
    for (const p of candidates.sort((a, b) => y[b] - y[a] || b - a)) {
      if (selected.every(q => Math.abs(p - q) >= distance)) selected.push(p);
    }
    return selected.filter(p => {
      let left = y[p], right = y[p];
      for (let i = p; i >= 0 && y[i] <= y[p]; i--) left = Math.min(left, y[i]);
      for (let i = p; i < y.length && y[i] <= y[p]; i++) right = Math.min(right, y[i]);
      return y[p] - Math.max(left, right) >= prominence;
    }).sort((a, b) => a - b);
  }
  function spectrum(y) {
    const n = 4 * 2 ** Math.ceil(Math.log2(y.length));
    const re = new Float64Array(n), im = new Float64Array(n);
    y.forEach((v, i) => { re[i] = v * (.5 - .5 * Math.cos(2 * Math.PI * i / y.length)); });
    for (let i = 1, j = 0; i < n; i++) {
      let bit = n >> 1;
      while (j & bit) { j ^= bit; bit >>= 1; }
      j ^= bit;
      if (i < j) [re[i], re[j]] = [re[j], re[i]];
    }
    for (let len = 2; len <= n; len <<= 1) {
      const ar = Math.cos(-2 * Math.PI / len), ai = Math.sin(-2 * Math.PI / len);
      for (let start = 0; start < n; start += len) {
        let wr = 1, wi = 0;
        for (let j = 0; j < len / 2; j++) {
          const a = start + j, b = a + len / 2;
          const vr = re[b] * wr - im[b] * wi, vi = re[b] * wi + im[b] * wr;
          re[b] = re[a] - vr; im[b] = im[a] - vi; re[a] += vr; im[a] += vi;
          const next = wr * ar - wi * ai; wi = wr * ai + wi * ar; wr = next;
        }
      }
    }
    return Array.from({length: n / 2 + 1}, (_, i) => [i * FS / n, re[i] ** 2 + im[i] ** 2]);
  }
  function emptyHR(status = 'collecting', span = 0) {
    return {heart_rate_bpm: null, heart_rate_status: status, heart_rate_updated_time_s: null,
      heart_rate_available_time_s: null, heart_rate_window_s: span, heart_rate_peak_count: 0,
      heart_rate_ibi_cv: null, heart_rate_spectral_bpm: null, heart_rate_spectral_concentration: null};
  }
  class HeartRateTracker {
    constructor() { this.segment = null; this.clear(); }
    clear(status = 'collecting') { this.history = []; this.lastUpdate = null; this.current = emptyHR(status); }
    feed(row) {
      if (this.segment !== row.segment) { this.clear(); this.segment = row.segment; }
      if (row.primary_bvp === null || !Number.isFinite(row.primary_bvp) || !row.ready) {
        this.clear(row.status === 'tracking' ? 'invalid_signal' : row.status); return this.current;
      }
      const last = this.history[this.history.length - 1];
      if (last && Math.abs(row.time_s - last.time_s - 1 / FS) > 1e-7) this.clear();
      this.history.push(row);
      while (this.history[0].time_s < row.time_s - 8 - 1e-9) this.history.shift();
      const span = row.time_s - this.history[0].time_s;
      if (span < 5 - 1e-9) this.current = emptyHR('collecting', span);
      else if (this.lastUpdate === null || row.time_s - this.lastUpdate >= 1 - 1e-9) {
        this.lastUpdate = row.time_s; this.current = this.estimate(row, span);
      }
      return this.current;
    }
    estimate(row, span) {
      const result = {...emptyHR('unreliable', span), heart_rate_updated_time_s: row.time_s,
        heart_rate_available_time_s: row.available_time_s};
      const arrivals = [...new Set(this.history.map(r => r.available_time_s))].sort((a, b) => a - b);
      const intervals = arrivals.slice(1).map((t, i) => t - arrivals[i]);
      if (intervals.length < 3 || 1 / percentile(intervals, .9) < 2.5 * 200 / 60) {
        result.heart_rate_status = 'low_frame_rate'; return result;
      }
      const raw = this.history.map(r => r.primary_bvp), y = detrend(raw), scale = std(y);
      if (scale < 1e-7) return result;
      const found = peaks(y, Math.floor(FS * 60 / 200), .6 * scale);
      result.heart_rate_peak_count = found.length;
      if (found.length < 4) return result;
      const times = found.map(p => {
        const denominator = y[p - 1] - 2 * y[p] + y[p + 1];
        const offset = Math.abs(denominator) > 1e-20 ? .5 * (y[p - 1] - y[p + 1]) / denominator : 0;
        return this.history[p].time_s + Math.max(-.5, Math.min(.5, offset)) / FS;
      });
      const ibi = times.slice(1).map((t, i) => t - times[i]), mid = median(ibi), bpm = 60 / mid;
      result.heart_rate_ibi_cv = std(ibi) / mean(ibi);
      if (bpm < 40 || bpm > 200 || result.heart_rate_ibi_cv > .2) return result;
      if (ibi.some(v => v < 60 / 200 - 1 / FS || v > 60 / 40 + 1 / FS)) return result;
      if (row.time_s - times[times.length - 1] > 1.8 * mid) return result;
      if (std(this.history.filter(r => r.time_s >= row.time_s - 1.5).map(r => r.primary_bvp)) < .1 * scale) return result;
      const psd = spectrum(y), band = psd.filter(p => p[0] >= .5 && p[0] <= 5);
      const search = psd.filter(p => p[0] >= 40 / 60 && p[0] <= 200 / 60);
      const dominant = search.reduce((a, b) => b[1] > a[1] ? b : a), halfWidth = Math.max(.15, 1.5 / span);
      const total = band.reduce((s, p) => s + p[1], 0);
      result.heart_rate_spectral_bpm = dominant[0] * 60;
      result.heart_rate_spectral_concentration = total > 0 ?
        band.filter(p => Math.abs(p[0] - dominant[0]) <= halfWidth).reduce((s, p) => s + p[1], 0) / total : 0;
      if (result.heart_rate_spectral_concentration < .5 || Math.abs(result.heart_rate_spectral_bpm - bpm) > Math.max(8, .12 * bpm)) return result;
      result.heart_rate_bpm = bpm; result.heart_rate_status = 'tracking'; return result;
    }
  }
  class PrimaryStream {
    constructor({qualityGate = true, adaptiveGap = true, warmup = 3} = {}) {
      this.qualityGate = qualityGate; this.adaptiveGap = adaptiveGap; this.warmup = warmup;
      this.lastTimestamp = null; this.frameIntervals = []; this.segment = -1; this.active = false;
      this.hr = new HeartRateTracker(); this.zi = SOS.map(() => [0, 0]);
    }
    get gapLimit() {
      if (!this.adaptiveGap || !this.frameIntervals.length) return .1;
      return Math.max(.1, Math.min(.5, 3 * Math.max(median(this.frameIntervals), median(this.frameIntervals.slice(-5)))));
    }
    sample(t, available, red, diff, log, bvp, ready, status) {
      const row = {time_s: t, available_time_s: available, red, normalized_difference: diff,
        log_reconstruction: log, primary_bvp: bvp, ready, status, segment: this.segment};
      return {...row, ...this.hr.feed(row)};
    }
    feed(t, red, green = 0) {
      if (!Number.isFinite(t) || (this.lastTimestamp !== null && t <= this.lastTimestamp)) throw new Error('帧时间必须严格递增');
      if (this.adaptiveGap && this.lastTimestamp !== null && t - this.lastTimestamp <= .5) {
        this.frameIntervals.push(t - this.lastTimestamp);
        if (this.frameIntervals.length > 60) this.frameIntervals.shift();
      }
      this.lastTimestamp = t;
      let reason = null;
      if (!Number.isFinite(red) || !Number.isFinite(green) || red <= 0) reason = 'invalid_intensity';
      else if (this.qualityGate && red < 8) reason = 'low_light';
      else if (this.qualityGate && red <= 2 * green) reason = 'no_finger';
      if (reason) { this.active = false; return [this.sample(t, t, red, null, null, null, false, reason)]; }
      if (!this.active || t - this.previousTime > this.gapLimit + 1e-12) {
        this.segment++; this.active = true; this.origin = t; this.nextIndex = 1;
        this.previousTime = t; this.previousRed = red; this.previousUniformRed = red;
        this.log = 0; this.zi = SOS.map(() => [0, 0]);
        const ready = this.warmup === 0;
        return [this.sample(t, t, red, null, 0, 0, ready, ready ? 'tracking' : 'warming_up')];
      }
      const rows = [];
      while (this.origin + this.nextIndex / FS <= t) {
        const grid = this.origin + this.nextIndex / FS;
        const weight = (grid - this.previousTime) / (t - this.previousTime);
        const value = this.previousRed + weight * (red - this.previousRed);
        const diff = (value - this.previousUniformRed) / (value + this.previousUniformRed);
        this.log += 2 * Math.atanh(diff);
        let v = -this.log;
        SOS.forEach((c, i) => {
          const output = c[0] * v + this.zi[i][0];
          this.zi[i][0] = c[1] * v - c[4] * output + this.zi[i][1];
          this.zi[i][1] = c[2] * v - c[5] * output; v = output;
        });
        const ready = grid - this.origin >= this.warmup;
        rows.push(this.sample(grid, t, value, diff, this.log, v, ready, ready ? 'tracking' : 'warming_up'));
        this.previousUniformRed = value; this.nextIndex++;
      }
      this.previousTime = t; this.previousRed = red; return rows;
    }
  }
  const api = {PrimaryStream, HeartRateTracker, FS, SOS};
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  else root.FingerPPG = api;
})(typeof globalThis !== 'undefined' ? globalThis : this);
