/* Shared mobile primary PPG and heart rate. No DOM, camera, network or platform dependency.
 * Fixed 60 Hz output grid; filter coefficients generated by scipy.signal.butter
 * (N=3, [0.5, 5] Hz, btype='bandpass', fs=60, output='sos').
 */
(function (root) {
  'use strict';
  const FS = 60;
  const SOS = [
    [.008598686086321939, .017197372172643877, .008598686086321939, 1, -1.4520619841171416, .6596484731374982],
    [1, 0, -1, 1, -1.5903260597027793, .612800788139932],
    [1, -2, 1, 1, -1.9521679192002526, .9550513432042125]
  ];
  function mean(a) { return a.reduce((s, v) => s + v, 0) / a.length; }
  function std(a) { const m = mean(a); return Math.sqrt(mean(a.map(v => (v - m) ** 2))); }
  function percentile(a, q) {
    const b = [...a].sort((x, y) => x - y), k = (b.length - 1) * q;
    const lo = Math.floor(k), hi = Math.ceil(k);
    return b[lo] + (b[hi] - b[lo]) * (k - lo);
  }
  const median = a => percentile(a, .5);
  function detrend(a) {
    const center = (a.length - 1) / 2, m = mean(a);
    let numerator = 0, denominator = 0;
    a.forEach((v, i) => { numerator += (i - center) * (v - m); denominator += (i - center) ** 2; });
    return a.map((v, i) => v - m - numerator / denominator * (i - center));
  }
  function peaks(y, distance, prominence) {
    const candidates = [];
    for (let i = 1; i < y.length - 1; i++) {
      if (y[i] <= y[i - 1]) continue;
      let end = i;
      while (end + 1 < y.length && y[end + 1] === y[i]) end++;
      if (end + 1 < y.length && y[end + 1] < y[i]) candidates.push(Math.floor((i + end) / 2));
      i = end;
    }
    const selected = [];
    for (const p of candidates.sort((a, b) => y[b] - y[a] || b - a)) {
      if (selected.every(q => Math.abs(p - q) >= distance)) selected.push(p);
    }
    return selected.filter(p => {
      let left = y[p], right = y[p];
      for (let i = p; i >= 0 && y[i] <= y[p]; i--) left = Math.min(left, y[i]);
      for (let i = p; i < y.length && y[i] <= y[p]; i++) right = Math.min(right, y[i]);
      return y[p] - Math.max(left, right) >= prominence;
    }).sort((a, b) => a - b);
  }
  function spectrum(y) {
    const n = 4 * 2 ** Math.ceil(Math.log2(y.length));
    const re = new Float64Array(n), im = new Float64Array(n);
    y.forEach((v, i) => { re[i] = v * (.5 - .5 * Math.cos(2 * Math.PI * i / y.length)); });
    for (let i = 1, j = 0; i < n; i++) {
      let bit = n >> 1;
      while (j & bit) { j ^= bit; bit >>= 1; }
      j ^= bit;
      if (i < j) [re[i], re[j]] = [re[j], re[i]];
    }
    for (let len = 2; len <= n; len <<= 1) {
      const ar = Math.cos(-2 * Math.PI / len), ai = Math.sin(-2 * Math.PI / len);
      for (let start = 0; start < n; start += len) {
        let wr = 1, wi = 0;
        for (let j = 0; j < len / 2; j++) {
          const a = start + j, b = a + len / 2;
          const vr = re[b] * wr - im[b] * wi, vi = re[b] * wi + im[b] * wr;
          re[b] = re[a] - vr; im[b] = im[a] - vi; re[a] += vr; im[a] += vi;
          const next = wr * ar - wi * ai; wi = wr * ai + wi * ar; wr = next;
        }
      }
    }
    return Array.from({length: n / 2 + 1}, (_, i) => [i * FS / n, re[i] ** 2 + im[i] ** 2]);
  }
  function emptyHR(status = 'collecting', span = 0) {
    return {heart_rate_bpm: null, heart_rate_status: status, heart_rate_updated_time_s: null,
      heart_rate_available_time_s: null, heart_rate_window_s: span, heart_rate_peak_count: 0,
      heart_rate_ibi_cv: null, heart_rate_spectral_bpm: null, heart_rate_spectral_concentration: null};
  }
  class HeartRateTracker {
    constructor() { this.segment = null; this.clear(); }
    clear(status = 'collecting') { this.history = []; this.lastUpdate = null; this.current = emptyHR(status); }
    feed(row) {
      if (this.segment !== row.segment) { this.clear(); this.segment = row.segment; }
      if (row.primary_bvp === null || !Number.isFinite(row.primary_bvp) || !row.ready) {
        this.clear(row.status === 'tracking' ? 'invalid_signal' : row.status); return this.current;
      }
      const last = this.history[this.history.length - 1];
      if (last && Math.abs(row.time_s - last.time_s - 1 / FS) > 1e-7) this.clear();
      this.history.push(row);
      while (this.history[0].time_s < row.time_s - 8 - 1e-9) this.history.shift();
      const span = row.time_s - this.history[0].time_s;
      if (span < 5 - 1e-9) this.current = emptyHR('collecting', span);
      else if (this.lastUpdate === null || row.time_s - this.lastUpdate >= 1 - 1e-9) {
        this.lastUpdate = row.time_s; this.current = this.estimate(row, span);
      }
      return this.current;
    }
    estimate(row, span) {
      const result = {...emptyHR('unreliable', span), heart_rate_updated_time_s: row.time_s,
        heart_rate_available_time_s: row.available_time_s};
      const arrivals = [...new Set(this.history.map(r => r.available_time_s))].sort((a, b) => a - b);
      const intervals = arrivals.slice(1).map((t, i) => t - arrivals[i]);
      if (intervals.length < 3 || 1 / percentile(intervals, .9) < 2.5 * 200 / 60) {
        result.heart_rate_status = 'low_frame_rate'; return result;
      }
      const raw = this.history.map(r => r.primary_bvp), y = detrend(raw), scale = std(y);
      if (scale < 1e-7) return result;
      const found = peaks(y, Math.floor(FS * 60 / 200), .6 * scale);
      result.heart_rate_peak_count = found.length;
      if (found.length < 4) return result;
      const times = found.map(p => {
        const denominator = y[p - 1] - 2 * y[p] + y[p + 1];
        const offset = Math.abs(denominator) > 1e-20 ? .5 * (y[p - 1] - y[p + 1]) / denominator : 0;
        return this.history[p].time_s + Math.max(-.5, Math.min(.5, offset)) / FS;
      });
      const ibi = times.slice(1).map((t, i) => t - times[i]), mid = median(ibi), bpm = 60 / mid;
      result.heart_rate_ibi_cv = std(ibi) / mean(ibi);
      if (bpm < 40 || bpm > 200 || result.heart_rate_ibi_cv > .2) return result;
      if (ibi.some(v => v < 60 / 200 - 1 / FS || v > 60 / 40 + 1 / FS)) return result;
      if (row.time_s - times[times.length - 1] > 1.8 * mid) return result;
      if (std(this.history.filter(r => r.time_s >= row.time_s - 1.5).map(r => r.primary_bvp)) < .1 * scale) return result;
      const psd = spectrum(y), band = psd.filter(p => p[0] >= .5 && p[0] <= 5);
      const search = psd.filter(p => p[0] >= 40 / 60 && p[0] <= 200 / 60);
      const dominant = search.reduce((a, b) => b[1] > a[1] ? b : a), halfWidth = Math.max(.15, 1.5 / span);
      const total = band.reduce((s, p) => s + p[1], 0);
      result.heart_rate_spectral_bpm = dominant[0] * 60;
      result.heart_rate_spectral_concentration = total > 0 ?
        band.filter(p => Math.abs(p[0] - dominant[0]) <= halfWidth).reduce((s, p) => s + p[1], 0) / total : 0;
      if (result.heart_rate_spectral_concentration < .5 || Math.abs(result.heart_rate_spectral_bpm - bpm) > Math.max(8, .12 * bpm)) return result;
      result.heart_rate_bpm = bpm; result.heart_rate_status = 'tracking'; return result;
    }
  }
  class PrimaryStream {
    constructor({qualityGate = true, adaptiveGap = true, warmup = 3} = {}) {
      this.qualityGate = qualityGate; this.adaptiveGap = adaptiveGap; this.warmup = warmup;
      this.lastTimestamp = null; this.frameIntervals = []; this.segment = -1; this.active = false;
      this.hr = new HeartRateTracker(); this.zi = SOS.map(() => [0, 0]);
    }
    get gapLimit() {
      if (!this.adaptiveGap || !this.frameIntervals.length) return .1;
      return Math.max(.1, Math.min(.5, 3 * Math.max(median(this.frameIntervals), median(this.frameIntervals.slice(-5)))));
    }
    sample(t, available, red, diff, log, bvp, ready, status) {
      const row = {time_s: t, available_time_s: available, red, normalized_difference: diff,
        log_reconstruction: log, primary_bvp: bvp, ready, status, segment: this.segment};
      return {...row, ...this.hr.feed(row)};
    }
    feed(t, red, green = 0) {
      if (!Number.isFinite(t) || (this.lastTimestamp !== null && t <= this.lastTimestamp)) throw new Error('帧时间必须严格递增');
      if (this.adaptiveGap && this.lastTimestamp !== null && t - this.lastTimestamp <= .5) {
        this.frameIntervals.push(t - this.lastTimestamp);
        if (this.frameIntervals.length > 60) this.frameIntervals.shift();
      }
      this.lastTimestamp = t;
      let reason = null;
      if (!Number.isFinite(red) || !Number.isFinite(green) || red <= 0) reason = 'invalid_intensity';
      else if (this.qualityGate && red < 8) reason = 'low_light';
      else if (this.qualityGate && red <= 2 * green) reason = 'no_finger';
      if (reason) { this.active = false; return [this.sample(t, t, red, null, null, null, false, reason)]; }
      if (!this.active || t - this.previousTime > this.gapLimit + 1e-12) {
        this.segment++; this.active = true; this.origin = t; this.nextIndex = 1;
        this.previousTime = t; this.previousRed = red; this.previousUniformRed = red;
        this.log = 0; this.zi = SOS.map(() => [0, 0]);
        const ready = this.warmup === 0;
        return [this.sample(t, t, red, null, 0, 0, ready, ready ? 'tracking' : 'warming_up')];
      }
      const rows = [];
      while (this.origin + this.nextIndex / FS <= t) {
        const grid = this.origin + this.nextIndex / FS;
        const weight = (grid - this.previousTime) / (t - this.previousTime);
        const value = this.previousRed + weight * (red - this.previousRed);
        const diff = (value - this.previousUniformRed) / (value + this.previousUniformRed);
        this.log += 2 * Math.atanh(diff);
        let v = -this.log;
        SOS.forEach((c, i) => {
          const output = c[0] * v + this.zi[i][0];
          this.zi[i][0] = c[1] * v - c[4] * output + this.zi[i][1];
          this.zi[i][1] = c[2] * v - c[5] * output; v = output;
        });
        const ready = grid - this.origin >= this.warmup;
        rows.push(this.sample(grid, t, value, diff, this.log, v, ready, ready ? 'tracking' : 'warming_up'));
        this.previousUniformRed = value; this.nextIndex++;
      }
      this.previousTime = t; this.previousRed = red; return rows;
    }
  }
  // HRV-style statistics of PPG pulse intervals (PRV), separate from the existing
  // primary/heart-rate path. No ECG R peaks or normal-beat classification is implied.
  function hrvTimeDomain(ppi) {
    if (ppi.length < 2 || ppi.some(value => !Number.isFinite(value) || value <= 0))
      return {mean_ppi_ms:null, sdrr_ms:null, rmssd_ms:null, pnn50_pct:null};
    const m = mean(ppi), differences = ppi.slice(1).map((value, i) => value-ppi[i]);
    return {mean_ppi_ms:m,
      sdrr_ms:Math.sqrt(ppi.reduce((sum,value)=>sum+(value-m)**2,0)/(ppi.length-1)),
      rmssd_ms:Math.sqrt(mean(differences.map(value=>value**2))),
      pnn50_pct:100*differences.filter(value=>Math.abs(value)>50+1e-7).length/differences.length};
  }
  function hrvFrequency(times, ppi) {
    const empty = {lf_power_ms2:null, hf_power_ms2:null, lf_hf_ratio:null,
      lf_hf_status:'insufficient_data', spectral_span_s:null, spectral_resolution_hz:null};
    if (times.length !== ppi.length || times.length < 3 || times.some((t,i)=>!Number.isFinite(t) || (i && t<=times[i-1])) ||
        ppi.some(value=>!Number.isFinite(value) || value<=0)) return empty;
    // Interpolate only between observed interval midpoints; never extrapolate or
    // bridge an invalid window. Interpolation here is spectral analysis, not data repair.
    const rate=4, values=[];
    let j=0;
    for(let i=0;times[0]+i/rate<=times[times.length-1]+1e-9;i++) {
      const t=times[0]+i/rate;
      while(j<times.length-2 && times[j+1]<t)j++;
      values.push(ppi[j]+(ppi[j+1]-ppi[j])*(t-times[j])/(times[j+1]-times[j]));
    }
    if(values.length<16)return empty;
    const y=detrend(values), n=y.length, size=512, df=rate/size;
    const result={...empty,spectral_span_s:(n-1)/rate,spectral_resolution_hz:rate/n};
    // A constant/near-constant train cannot support a meaningful LF/HF ratio.
    if(mean(y.map(value=>value**2))<1) return {...result,lf_hf_status:'low_variance'};
    const weights=y.map((_,i)=>.5-.5*Math.cos(2*Math.PI*i/n));
    const normalization=rate*weights.reduce((sum,w)=>sum+w*w,0), density=[];
    for(let k=0;k<=Math.ceil(.4/df);k++) {
      let re=0,im=0;
      y.forEach((value,i)=>{const phase=2*Math.PI*k*i/size;re+=value*weights[i]*Math.cos(phase);im-=value*weights[i]*Math.sin(phase);});
      density.push((k===0?1:2)*(re*re+im*im)/normalization);
    }
    const integrate=(low,high)=>{
      let sum=0;
      for(let k=1;k<density.length;k++) {
        const x=(k-1)*df, a=Math.max(low,x), b=Math.min(high,k*df);
        if(b<=a)continue;
        const at=f=>density[k-1]+(density[k]-density[k-1])*(f-x)/df;
        sum+=(at(a)+at(b))*(b-a)/2;
      }
      return sum;
    };
    const lf=integrate(.04,.15),hf=integrate(.15,.4);
    return {...result,lf_power_ms2:lf,hf_power_ms2:hf,
      lf_hf_ratio:hf>1e-6?lf/hf:null,lf_hf_status:hf>1e-6?'exploratory_30s':'insufficient_hf'};
  }
  function emptyHRV(status='collecting',span=0) {
    return {time_s:null,available_time_s:null,status,window_s:30,valid_signal_s:span,
      interval_count:0,interval_span_s:null,rejected_interval_count:0,
      mean_ppi_ms:null,sdrr_ms:null,rmssd_ms:null,pnn50_pct:null,
      lf_power_ms2:null,hf_power_ms2:null,lf_hf_ratio:null,lf_hf_status:'insufficient_data',
      spectral_span_s:null,spectral_resolution_hz:null,pulse_times_s:[],ppi_ms:[]};
  }
  class HRVTracker {
    constructor() {this.segment=null;this.clear();}
    clear(status='collecting') {this.history=[];this.lastUpdate=null;this.current=emptyHRV(status);}
    feed(row) {
      const segmentChanged=this.segment!==row.segment;
      if(segmentChanged){this.clear();this.segment=row.segment;}
      if(!row.ready || !Number.isFinite(row.primary_bvp)) {
        const status=row.status==='tracking'?'invalid_signal':row.status;
        const changed=segmentChanged || this.history.length>0 || this.current.status!==status;
        this.clear(status);this.current.time_s=row.time_s;this.current.available_time_s=row.available_time_s;
        return changed?this.current:null;
      }
      const last=this.history[this.history.length-1];
      if(last && Math.abs(row.time_s-last.time_s-1/FS)>1e-7)this.clear();
      this.history.push(row);
      while(this.history[0].time_s<row.time_s-30-1e-9)this.history.shift();
      const span=row.time_s-this.history[0].time_s;
      if(this.lastUpdate!==null && row.time_s-this.lastUpdate<5-1e-9)return null;
      this.lastUpdate=row.time_s;
      this.current=span<30-1e-7?emptyHRV('collecting',span):this.estimate(row);
      this.current.time_s=row.time_s;this.current.available_time_s=row.available_time_s;
      return this.current;
    }
    estimate(row) {
      const result=emptyHRV('unreliable',30);
      const arrivals=[...new Set(this.history.map(r=>r.available_time_s))].sort((a,b)=>a-b);
      const deltas=arrivals.slice(1).map((t,i)=>t-arrivals[i]);
      // Application quality thresholds, not a claim that a camera is ECG-accurate.
      if(deltas.length<3 || percentile(deltas,.9)>1/25+1e-9 || Math.max(...deltas)>.1+1e-9)
        return {...result,status:'low_frame_rate'};
      const y=detrend(this.history.map(r=>r.primary_bvp)), scale=std(y);
      if(scale<1e-7 || row.heart_rate_status!=='tracking')return result;
      const found=peaks(y,Math.floor(FS*60/200),.6*scale);
      const times=found.map(p=>{
        const denominator=y[p-1]-2*y[p]+y[p+1];
        const offset=Math.abs(denominator)>1e-20?.5*(y[p-1]-y[p+1])/denominator:0;
        return this.history[p].time_s+Math.max(-.5,Math.min(.5,offset))/FS;
      });
      const ppi=times.slice(1).map((t,i)=>(t-times[i])*1000);
      Object.assign(result,{pulse_times_s:times,ppi_ms:ppi,interval_count:ppi.length,
        interval_span_s:times.length>1?times[times.length-1]-times[0]:0});
      if(ppi.length<15 || result.interval_span_s<26)return {...result,status:'insufficient_beats'};
      // Reject the whole window rather than deleting beats and creating false
      // successive differences across an artifact. No ectopic-beat correction.
      result.rejected_interval_count=ppi.filter((value,i)=>{
        const local=median(ppi.slice(Math.max(0,i-2),Math.min(ppi.length,i+3)));
        return value<300 || value>1500 || Math.abs(value-local)>.2*local;
      }).length;
      if(result.rejected_interval_count)return {...result,status:'artifact'};
      const intervalTimes=times.slice(1).map((t,i)=>(t+times[i])/2);
      return {...result,status:'tracking',...hrvTimeDomain(ppi),...hrvFrequency(intervalTimes,ppi)};
    }
  }
  const api = {PrimaryStream, HeartRateTracker, HRVTracker, hrvTimeDomain, hrvFrequency, FS, SOS};
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  else root.FingerPPG = api;
})(typeof globalThis !== 'undefined' ? globalThis : this);
